replicaCount: 1

image:
  repository: dungeonomics
  tag: dev
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 8000

ingress:
  enabled: true
  className: nginx
  hosts:
    - host: ""
      paths:
        - path: /
          pathType: Prefix

django:
  debug: false
  adminPath: admin
  allowedHosts: "localhost,127.0.0.1"

secret:
  djangoSecretKey: change-me-in-prod

useExternalPostgres: true
postgresql:
  enabled: false

database:
  host: generic-postgres-postgresql.default.svc.cluster.local
  port: 5432
  name: dungeonomics
  user: postgres
  password: postgres

# useExternalPostgres: false
# postgresql:
#   enabled: true
# 
#   auth:
#     database: dungeonomics
#     username: dungeonomics
#     password: dungeonomics
# 
#   primary:
#     persistence:
#       enabled: true
#       size: 5Gi
#
# database:
#  name: dungeonomics
#  host: dungeonomics-postgresql
#  port: 5432
#  user: postgres
#  password: postgres