apiVersion: v1
kind: ConfigMap
metadata:
  name: dungeonomics-config
data:
  DB_NAME: dungeonomics
  DB_HOST: postgres-postgresql.postgres.svc.cluster.local
  DB_PORT: "5432"
  DJANGO_DEBUG: "False"
  ALLOWED_HOSTS: "localhost,127.0.0.1"
  DJANGO_ADMIN_PATH: "admin"