apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "dungeonomics.fullname" . }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "dungeonomics.name" . }}
  template:
    metadata:
      labels:
        app: {{ include "dungeonomics.name" . }}
    spec:
      initContainers:
        - name: wait-and-init-postgres
          image: alpine/psql:latest
          imagePullPolicy: IfNotPresent
          env:
            - name: PGPASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "dungeonomics.fullname" . }}-secrets
                  key: DB_PASSWORD
          command:
            - sh
            - -c
            - |
              until pg_isready -h {{ .Values.database.host }} -p {{ .Values.database.port }} -U {{ .Values.database.user }}; do
                sleep 2
              done

              {{- if .Values.useExternalPostgres }}
              DB_EXISTS=$(psql -h {{ .Values.database.host }} -p {{ .Values.database.port }} -U {{ .Values.database.user }} -d postgres -tAc "SELECT 1 FROM pg_database WHERE datname='{{ .Values.database.name }}'")
              if [ "$DB_EXISTS" != "1" ]; then
                psql -h {{ .Values.database.host }} -p {{ .Values.database.port }} -U {{ .Values.database.user }} -d postgres -c "CREATE DATABASE {{ .Values.database.name }};"
              fi
              {{- end }}
      containers:
        - name: web
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: 8000
          command:
            - sh
            - -c
            - |
              python manage.py migrate --noinput
              python manage.py collectstatic --noinput
              gunicorn dungeonomics.wsgi:application --bind=0.0.0.0:8000 --workers=3
          envFrom:
            - configMapRef:
                name: {{ include "dungeonomics.fullname" . }}-config
            - secretRef:
                name: {{ include "dungeonomics.fullname" . }}-secrets